module.exports = {
	blackGradient: require("../images/blackgradient.png"),
	whiteGradient: require("../images/whitegradient.png"),
	overviewIcon: require("../images/plant.png"),
	homeIcon: require("../images/home.png"),
	calIcon: require("../images/calendar.png"),
	settingsIcon: require("../images/spanner.png"),
	uploadIcon: require("../images/upload.png"),
	writeIcon: require("../images/write-simple.png"),
	phoneIcon: require("../images/phone.png"),
	backIcon: require("../images/back.png"),
	disclosureIcon: require("../images/disclosure.png"),
	assignmentIcon: require("../images/assignment.png"),
	butterfly: require("../images/butterfly.png"),
	xIcon: require("../images/x.png"),
	plusIcon: require("../images/plus.png"),
	personIcon: require("../images/person.jpeg"),
};
